on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout controlPanel rep
      uses: actions/checkout@v2
    - name: esp-idf build
      uses: icodk/esp-idf-ci-action@1
